---
- hosts: VPS
  remote_user: root
    
  tasks:
  - name: APT-GET UPDATE
    apt: update_cache=yes cache_valid_time=7200
  - name: Installation Tools
    apt: name={{item}} state=present
    with_items:
      - htop
      - vim
      - ufw
      - rkhunter
      - fail2ban
      - mutt
      - logwatch
      - logrotate
      - openvpn
      - portsentry
      
  - name: User Account Creation
    user: name=sladerz comment=SladerZ shell=/bin/bash createhome=yes

  - name: Download OpenVpn-install
    get_url: url=https://raw.githubusercontent.com/Nyr/openvpn-install/master/openvpn-install.sh dest=/root mode=0744

  - replace: dest=/etc/default/portsentry regexp='=\"tcp\"' replace='=\"atcp\"' 
  - replace: dest=/etc/default/portsentry regexp='=\"udp\"' replace='=\"audp\"'
  - replace: dest=/etc/portsentry/portsentry.conf regexp='BLOCK_UDP=\"0\"' replace='BLOCK_UDP=\"1\"'
  - replace: dest=/etc/portsentry/portsentry.conf regexp='BLOCK_TCP=\"0\"' replace='BLOCK_TCP=\"1\"'
  - replace: dest=/etc/portsentry/portsentry.conf regexp='# KILL_ROUTE=' replace='KILL_ROUTE=' 

  - service: name=portsentry  state=started enabled=yes
